# 01 — Binance Market Data Exploration

## Goal

Understand the structure of Binance market data before building the data pipeline.

Tasks:

- Inspect Binance API structure
- Understand trade messages
- Understand order book depth updates
- Examine timestamps and ordering
- Identify fields needed for limit order book reconstruction

This notebook is **exploratory**.  
Production code will later move into:


---

# 1. Exchange and Market Selection

For this project we use:

Exchange: Binance
Pair: BTCUSDT

- High liquidity
- Access to limit order book
- Good api support
- Free to use



# Load Required Libraries

In [223]:
import pandas as pd
import numpy as np
from binance.client import Client
import time
import black

# Get Order Book
I want to just get data one time to allow for reproducible results

In [224]:
client = Client()

Check latency, since binance doesnt give time with the non websocket depth snapshots

In [225]:
t0 = int(time.time() * 1000)

depth = client.get_order_book(symbol="BTCUSDT")

t1 = int(time.time() * 1000)

rtt = t1 - t0
latency = rtt / 2
latency

119.0

Latency ~ 151 ms so using 1 second intervals for snapshots should in general be fine (missing intra second data) - future update is to add in websocket intrasecond info

In [226]:
depth_samples = []

for i in range(5):
    timestamp = int(time.time() * 1000)
    depth = client.get_order_book(symbol="BTCUSDT", limit=100)
    bids = depth["bids"]
    asks = depth["asks"]
    depth_samples.append(
        {
            "timestamp": timestamp,
            "lastUpdateId": depth["lastUpdateId"],
            "bids": depth["bids"],
            "asks": depth["asks"],
        }
    )
    time.sleep(1)
trades = client.get_recent_trades(symbol="BTCUSDT", limit=1000)

depth_samples

[{'timestamp': 1773047452780,
  'lastUpdateId': 89730922218,
  'bids': [['67621.99000000', '1.18578000'],
   ['67621.98000000', '0.00008000'],
   ['67621.82000000', '0.13316000'],
   ['67621.68000000', '0.00009000'],
   ['67620.00000000', '0.00008000'],
   ['67619.97000000', '0.00008000'],
   ['67619.88000000', '0.00009000'],
   ['67619.25000000', '0.00008000'],
   ['67619.24000000', '0.05153000'],
   ['67619.22000000', '0.00008000'],
   ['67619.21000000', '0.02737000'],
   ['67619.20000000', '0.00625000'],
   ['67618.93000000', '0.00236000'],
   ['67618.77000000', '0.03044000'],
   ['67618.20000000', '0.00008000'],
   ['67617.50000000', '0.00200000'],
   ['67617.46000000', '0.00012000'],
   ['67617.34000000', '0.00009000'],
   ['67617.12000000', '0.00008000'],
   ['67617.00000000', '0.00009000'],
   ['67616.98000000', '0.00022000'],
   ['67616.80000000', '0.00008000'],
   ['67616.64000000', '0.00017000'],
   ['67616.21000000', '0.00139000'],
   ['67615.97000000', '0.00014000'],
   ['67615.88000000', '0.00015000'],
   ['67615.80000000', '0.00200000'],
   ['67615.33000000', '0.04833000'],
   ['67615.32000000', '0.15978000'],
   ['67615.22000000', '0.00148000'],
   ['67615.09000000', '0.00031000'],
   ['67615.06000000', '0.00008000'],
   ['67615.05000000', '0.02922000'],
   ['67614.99000000', '0.00009000'],
   ['67614.80000000', '0.00009000'],
   ['67614.35000000', '0.00008000'],
   ['67614.10000000', '0.00200000'],
   ['67613.54000000', '0.00015000'],
   ['67613.28000000', '0.00008000'],
   ['67612.61000000', '0.00747000'],
   ['67612.40000000', '0.00200000'],
   ['67612.26000000', '0.00009000'],
   ['67612.08000000', '2.79072000'],
   ['67612.06000000', '0.70950000'],
   ['67611.96000000', '0.00147000'],
   ['67611.60000000', '0.00009000'],
   ['67611.28000000', '0.00739000'],
   ['67611.27000000', '0.00148000'],
   ['67611.12000000', '0.00151000'],
   ['67610.70000000', '0.00200000'],
   ['67610.68000000', '0.00012000'],
   ['67610.49000000', '0.00008000'],
   ['67610.40000000', '0.00009000'],
   ['67610.16000000', '0.00015000'],
   ['67610.11000000', '0.00008000'],
   ['67610.00000000', '0.00120000'],
   ['67609.92000000', '0.00008000'],
   ['67609.72000000', '0.00009000'],
   ['67609.54000000', '0.00022000'],
   ['67609.29000000', '0.29136000'],
   ['67609.27000000', '0.70950000'],
   ['67609.00000000', '0.00200000'],
   ['67608.90000000', '0.00473000'],
   ['67608.65000000', '0.00028000'],
   ['67608.45000000', '0.02299000'],
   ['67608.24000000', '0.00031000'],
   ['67608.09000000', '0.00591000'],
   ['67608.00000000', '0.00120000'],
   ['67607.76000000', '0.00015000'],
   ['67607.30000000', '0.00200000'],
   ['67607.23000000', '0.00589000'],
   ['67607.18000000', '0.00009000'],
   ['67606.64000000', '0.00008000'],
   ['67606.56000000', '0.00017000'],
   ['67606.53000000', '0.00192000'],
   ['67606.35000000', '0.80758000'],
   ['67606.34000000', '2.70507000'],
   ['67606.00000000', '0.00120000'],
   ['67605.92000000', '0.00260000'],
   ['67605.84000000', '0.09873000'],
   ['67605.74000000', '0.00453000'],
   ['67605.67000000', '0.02000000'],
   ['67605.60000000', '0.00200000'],
   ['67605.59000000', '0.02000000'],
   ['67605.58000000', '0.02000000'],
   ['67605.26000000', '0.00015000'],
   ['67605.03000000', '0.00008000'],
   ['67605.00000000', '0.04000000'],
   ['67604.93000000', '0.00147000'],
   ['67604.92000000', '0.04000000'],
   ['67604.64000000', '0.00009000'],
   ['67604.50000000', '0.00008000'],
   ['67604.41000000', '0.00147000'],
   ['67604.33000000', '0.02000000'],
   ['67604.00000000', '0.00120000'],
   ['67603.90000000', '0.00212000'],
   ['67603.80000000', '0.00009000'],
   ['67603.56000000', '0.00015000'],
   ['67603.29000000', '0.02000000'],
   ['67603.20000000', '0.00008000']],
  'asks': [['67622.00000000', '0.91606000'],
   ['67622.01000000', '0.00016000'],
   ['67622.75000000', '0.00008000'],
   ['67623.36000000', '0.00008000'],
   ['67624.19000000', '0.00016000'],
   ['67624.20000000', '0.03109000'],
   ['67624.21000000', '0.00016000'],
   ['67624.79000000', '0.00008000'],
   ['67624.80000000', '0.00663000'],
   ['67624.81000000', '0.00008000'],
   ['67624.91000000', '0.03283000'],
   ['67626.00000000', '0.00200000'],
   ['67626.72000000', '0.00008000'],
   ['67626.81000000', '0.00024000'],
   ['67626.82000000', '0.03728000'],
   ['67626.94000000', '0.00016000'],
   ['67626.95000000', '0.00016000'],
   ['67627.50000000', '0.00009000'],
   ['67627.69000000', '0.00016000'],
   ['67627.70000000', '0.00224000'],
   ['67627.71000000', '0.03009000'],
   ['67629.40000000', '0.00200000'],
   ['67629.53000000', '0.01479000'],
   ['67629.84000000', '0.00012000'],
   ['67630.01000000', '0.00031000'],
   ['67630.04000000', '0.00009000'],
   ['67630.08000000', '0.00008000'],
   ['67630.09000000', '0.00008000'],
   ['67630.20000000', '0.00009000'],
   ['67630.44000000', '0.00015000'],
   ['67630.94000000', '0.00048000'],
   ['67631.05000000', '0.00189000'],
   ['67631.09000000', '0.00739000'],
   ['67631.10000000', '0.00200000'],
   ['67631.52000000', '0.01441000'],
   ['67631.56000000', '0.71461000'],
   ['67631.57000000', '0.15978000'],
   ['67631.71000000', '0.00048000'],
   ['67631.74000000', '1.99557000'],
   ['67631.75000000', '0.02000000'],
   ['67631.77000000', '0.15000000'],
   ['67632.43000000', '0.00008000'],
   ['67632.44000000', '0.08348000'],
   ['67632.45000000', '0.04753000'],
   ['67632.48000000', '0.00355000'],
   ['67632.58000000', '0.00009000'],
   ['67632.80000000', '0.00200000'],
   ['67633.44000000', '0.00008000'],
   ['67633.61000000', '0.00008000'],
   ['67634.16000000', '0.30971000'],
   ['67634.17000000', '0.12904000'],
   ['67634.50000000', '0.00200000'],
   ['67634.99000000', '0.00420000'],
   ['67635.26000000', '0.00015000'],
   ['67635.40000000', '0.70950000'],
   ['67635.64000000', '0.05188000'],
   ['67636.01000000', '0.03717000'],
   ['67636.20000000', '0.00200000'],
   ['67636.27000000', '0.02957000'],
   ['67636.53000000', '0.00012000'],
   ['67636.80000000', '0.00026000'],
   ['67636.96000000', '0.00147000'],
   ['67637.35000000', '0.03800000'],
   ['67637.46000000', '0.00008000'],
   ['67637.61000000', '0.00031000'],
   ['67637.66000000', '0.00009000'],
   ['67637.86000000', '0.05636000'],
   ['67637.90000000', '0.00200000'],
   ['67638.13000000', '0.06600000'],
   ['67638.15000000', '1.78472000'],
   ['67638.32000000', '0.00148000'],
   ['67638.35000000', '0.00190000'],
   ['67638.56000000', '0.00274000'],
   ['67638.64000000', '0.00015000'],
   ['67638.65000000', '0.00009000'],
   ['67638.66000000', '0.00022000'],
   ['67639.19000000', '1.99557000'],
   ['67639.20000000', '0.29573000'],
   ['67639.22000000', '0.15970000'],
   ['67639.25000000', '0.03800000'],
   ['67639.40000000', '0.09649000'],
   ['67639.60000000', '0.00200000'],
   ['67639.97000000', '0.03000000'],
   ['67640.00000000', '0.00040000'],
   ['67640.04000000', '0.00739000'],
   ['67640.05000000', '0.03800000'],
   ['67640.16000000', '0.00008000'],
   ['67640.20000000', '0.00009000'],
   ['67640.52000000', '0.02956000'],
   ['67640.59000000', '0.00236000'],
   ['67640.60000000', '0.00355000'],
   ['67640.89000000', '0.00015000'],
   ['67641.07000000', '0.00532000'],
   ['67641.20000000', '0.66627000'],
   ['67641.21000000', '0.71069000'],
   ['67641.30000000', '0.00200000'],
   ['67641.32000000', '0.00008000'],
   ['67641.34000000', '0.00739000'],
   ['67641.84000000', '0.00009000'],
   ['67642.00000000', '0.00040000']]},
 {'timestamp': 1773047454017,
  'lastUpdateId': 89730923122,
  'bids': [['67621.99000000', '0.35148000'],
   ['67621.98000000', '0.00048000'],
   ['67621.68000000', '0.00009000'],
   ['67620.02000000', '0.00260000'],
   ['67620.00000000', '0.00008000'],
   ['67619.97000000', '0.00008000'],
   ['67619.88000000', '0.00009000'],
   ['67619.25000000', '0.00024000'],
   ['67619.24000000', '0.05153000'],
   ['67619.22000000', '0.00024000'],
   ['67619.21000000', '0.02745000'],
   ['67619.20000000', '0.00425000'],
   ['67618.93000000', '0.00236000'],
   ['67618.83000000', '0.00016000'],
   ['67618.82000000', '0.03076000'],
   ['67618.20000000', '0.00008000'],
   ['67617.46000000', '0.00012000'],
   ['67617.34000000', '0.00009000'],
   ['67616.64000000', '0.00017000'],
   ['67616.47000000', '0.00599000'],
   ['67616.21000000', '0.00139000'],
   ['67615.98000000', '0.00016000'],
   ['67615.97000000', '0.13324000'],
   ['67615.88000000', '0.00015000'],
   ['67615.33000000', '0.00008000'],
   ['67615.32000000', '0.15978000'],
   ['67615.22000000', '0.00148000'],
   ['67615.05000000', '0.02930000'],
   ['67615.03000000', '0.00031000'],
   ['67614.99000000', '0.00009000'],
   ['67614.80000000', '0.00009000'],
   ['67614.35000000', '0.00008000'],
   ['67614.10000000', '0.00200000'],
   ['67613.90000000', '0.04002000'],
   ['67613.54000000', '0.00015000'],
   ['67613.28000000', '0.00008000'],
   ['67612.95000000', '0.00047000'],
   ['67612.75000000', '0.00048000'],
   ['67612.48000000', '0.00151000'],
   ['67612.40000000', '0.00200000'],
   ['67612.26000000', '0.00009000'],
   ['67612.11000000', '0.21563000'],
   ['67612.10000000', '0.70950000'],
   ['67611.96000000', '0.00147000'],
   ['67611.60000000', '0.00009000'],
   ['67611.27000000', '0.00148000'],
   ['67610.93000000', '0.00026000'],
   ['67610.70000000', '0.00200000'],
   ['67610.68000000', '0.00012000'],
   ['67610.49000000', '0.00008000'],
   ['67610.40000000', '0.00009000'],
   ['67610.17000000', '0.00739000'],
   ['67610.16000000', '0.00015000'],
   ['67610.11000000', '0.00008000'],
   ['67610.00000000', '0.00120000'],
   ['67609.92000000', '0.00008000'],
   ['67609.72000000', '0.00009000'],
   ['67609.54000000', '0.00022000'],
   ['67609.32000000', '0.29027000'],
   ['67609.30000000', '0.70950000'],
   ['67609.00000000', '0.00200000'],
   ['67608.90000000', '0.00473000'],
   ['67608.45000000', '0.02299000'],
   ['67608.24000000', '0.00031000'],
   ['67608.09000000', '0.00591000'],
   ['67608.00000000', '0.00120000'],
   ['67607.76000000', '0.00015000'],
   ['67607.30000000', '0.00200000'],
   ['67607.18000000', '0.00009000'],
   ['67606.64000000', '0.00008000'],
   ['67606.56000000', '0.00017000'],
   ['67606.53000000', '0.00192000'],
   ['67606.49000000', '0.02000000'],
   ['67606.35000000', '0.80758000'],
   ['67606.34000000', '0.70950000'],
   ['67606.00000000', '0.00120000'],
   ['67605.92000000', '0.00260000'],
   ['67605.84000000', '0.09873000'],
   ['67605.67000000', '0.02000000'],
   ['67605.60000000', '1.99757000'],
   ['67605.59000000', '0.02000000'],
   ['67605.58000000', '0.02000000'],
   ['67605.27000000', '0.00739000'],
   ['67605.26000000', '0.00015000'],
   ['67605.03000000', '0.00008000'],
   ['67605.00000000', '0.04000000'],
   ['67604.93000000', '0.00147000'],
   ['67604.92000000', '0.04000000'],
   ['67604.64000000', '0.00009000'],
   ['67604.50000000', '0.00008000'],
   ['67604.41000000', '0.00147000'],
   ['67604.33000000', '0.02000000'],
   ['67604.00000000', '0.00120000'],
   ['67603.90000000', '0.00212000'],
   ['67603.80000000', '0.00009000'],
   ['67603.56000000', '0.00015000'],
   ['67603.29000000', '0.02000000'],
   ['67603.20000000', '0.00008000'],
   ['67603.11000000', '0.70950000'],
   ['67602.97000000', '1.23428000']],
  'asks': [['67622.00000000', '1.46163000'],
   ['67622.01000000', '0.00016000'],
   ['67622.60000000', '0.00200000'],
   ['67622.75000000', '0.00008000'],
   ['67623.36000000', '0.00008000'],
   ['67624.20000000', '0.00008000'],
   ['67624.30000000', '0.00200000'],
   ['67624.79000000', '0.00008000'],
   ['67624.80000000', '0.00663000'],
   ['67624.81000000', '0.00008000'],
   ['67624.85000000', '0.03702000'],
   ['67624.86000000', '0.03016000'],
   ['67624.93000000', '0.03270000'],
   ['67625.29000000', '0.00022000'],
   ['67626.00000000', '0.00200000'],
   ['67626.71000000', '0.00755000'],
   ['67626.72000000', '0.00008000'],
   ['67626.81000000', '0.00008000'],
   ['67626.82000000', '0.03728000'],
   ['67627.08000000', '0.02016000'],
   ['67627.14000000', '0.01505000'],
   ['67627.50000000', '0.00009000'],
   ['67627.70000000', '0.00200000'],
   ['67627.71000000', '0.02993000'],
   ['67628.40000000', '0.00151000'],
   ['67629.40000000', '0.00200000'],
   ['67629.53000000', '0.01479000'],
   ['67629.75000000', '0.00008000'],
   ['67629.84000000', '0.00012000'],
   ['67630.01000000', '0.00031000'],
   ['67630.04000000', '0.00009000'],
   ['67630.08000000', '0.00008000'],
   ['67630.09000000', '0.00008000'],
   ['67630.20000000', '0.00009000'],
   ['67630.42000000', '0.00008000'],
   ['67630.44000000', '0.00015000'],
   ['67630.76000000', '0.00048000'],
   ['67631.10000000', '0.00200000'],
   ['67631.51000000', '0.22339000'],
   ['67631.52000000', '0.01441000'],
   ['67631.56000000', '0.69459000'],
   ['67631.57000000', '0.15978000'],
   ['67631.77000000', '0.04000000'],
   ['67632.14000000', '0.00147000'],
   ['67632.43000000', '0.00008000'],
   ['67632.44000000', '0.08348000'],
   ['67632.45000000', '0.04006000'],
   ['67632.48000000', '0.05991000'],
   ['67632.58000000', '0.00009000'],
   ['67632.80000000', '0.00200000'],
   ['67633.44000000', '0.00008000'],
   ['67633.61000000', '0.00008000'],
   ['67633.75000000', '2.02557000'],
   ['67634.13000000', '0.51340000'],
   ['67634.14000000', '0.70950000'],
   ['67634.15000000', '0.00739000'],
   ['67634.17000000', '0.12904000'],
   ['67634.23000000', '0.00532000'],
   ['67634.37000000', '0.08000000'],
   ['67634.50000000', '0.00200000'],
   ['67634.99000000', '0.00420000'],
   ['67635.12000000', '0.00009000'],
   ['67635.26000000', '0.00015000'],
   ['67635.63000000', '0.00739000'],
   ['67635.64000000', '0.05188000'],
   ['67635.88000000', '0.03000000'],
   ['67636.13000000', '0.02600000'],
   ['67636.20000000', '0.00200000'],
   ['67636.27000000', '0.02957000'],
   ['67636.53000000', '0.00012000'],
   ['67636.63000000', '0.29574000'],
   ['67636.70000000', '0.53233000'],
   ['67636.80000000', '0.02426000'],
   ['67636.96000000', '0.00147000'],
   ['67637.14000000', '0.02800000'],
   ['67637.34000000', '0.03697000'],
   ['67637.35000000', '0.03800000'],
   ['67637.46000000', '0.00008000'],
   ['67637.61000000', '0.00031000'],
   ['67637.66000000', '0.00009000'],
   ['67637.81000000', '0.03664000'],
   ['67637.90000000', '0.00200000'],
   ['67638.12000000', '0.70950000'],
   ['67638.13000000', '0.06600000'],
   ['67638.15000000', '0.68831000'],
   ['67638.32000000', '0.00148000'],
   ['67638.35000000', '0.00190000'],
   ['67638.56000000', '0.00274000'],
   ['67638.63000000', '0.36239000'],
   ['67638.64000000', '0.00015000'],
   ['67638.65000000', '0.00009000'],
   ['67638.66000000', '0.00022000'],
   ['67639.19000000', '1.99557000'],
   ['67639.22000000', '0.15970000'],
   ['67639.25000000', '0.03800000'],
   ['67639.60000000', '0.00200000'],
   ['67639.97000000', '0.03000000'],
   ['67640.00000000', '0.00040000'],
   ['67640.05000000', '0.03800000'],
   ['67640.16000000', '0.00008000']]},
 {'timestamp': 1773047455255,
  'lastUpdateId': 89730923596,
  'bids': [['67621.99000000', '0.90717000'],
   ['67621.98000000', '0.00024000'],
   ['67621.68000000', '0.00009000'],
   ['67620.90000000', '0.00024000'],
   ['67620.89000000', '0.04010000'],
   ['67620.73000000', '0.00008000'],
   ['67620.02000000', '0.00260000'],
   ['67620.00000000', '0.00008000'],
   ['67619.97000000', '0.00008000'],
   ['67619.88000000', '0.00009000'],
   ['67619.25000000', '0.00024000'],
   ['67619.24000000', '0.05153000'],
   ['67619.22000000', '0.00024000'],
   ['67619.21000000', '0.02745000'],
   ['67619.20000000', '0.00633000'],
   ['67618.93000000', '0.00236000'],
   ['67618.83000000', '0.00016000'],
   ['67618.82000000', '0.03076000'],
   ['67618.31000000', '0.00008000'],
   ['67618.20000000', '0.00008000'],
   ['67618.10000000', '0.00008000'],
   ['67618.09000000', '0.13324000'],
   ['67617.50000000', '0.00200000'],
   ['67617.46000000', '0.00012000'],
   ['67617.34000000', '0.00009000'],
   ['67617.00000000', '0.00009000'],
   ['67616.64000000', '0.00017000'],
   ['67616.61000000', '0.00022000'],
   ['67616.21000000', '0.00139000'],
   ['67615.98000000', '0.04984000'],
   ['67615.88000000', '0.00015000'],
   ['67615.80000000', '0.00200000'],
   ['67615.32000000', '0.15970000'],
   ['67615.22000000', '0.00148000'],
   ['67615.03000000', '0.00031000'],
   ['67614.99000000', '0.00009000'],
   ['67614.98000000', '0.02902000'],
   ['67614.80000000', '0.00009000'],
   ['67614.35000000', '0.00008000'],
   ['67614.10000000', '0.00200000'],
   ['67613.54000000', '0.00015000'],
   ['67613.42000000', '0.00048000'],
   ['67613.28000000', '0.00008000'],
   ['67612.48000000', '0.00151000'],
   ['67612.41000000', '0.00739000'],
   ['67612.40000000', '0.00200000'],
   ['67612.26000000', '0.00009000'],
   ['67612.16000000', '0.75284000'],
   ['67612.15000000', '1.99557000'],
   ['67612.10000000', '0.70950000'],
   ['67611.96000000', '0.00147000'],
   ['67611.60000000', '0.00009000'],
   ['67611.27000000', '0.00148000'],
   ['67610.93000000', '0.00026000'],
   ['67610.70000000', '0.00200000'],
   ['67610.68000000', '0.00012000'],
   ['67610.49000000', '0.00008000'],
   ['67610.40000000', '0.00009000'],
   ['67610.17000000', '0.00739000'],
   ['67610.16000000', '0.00015000'],
   ['67610.11000000', '0.00008000'],
   ['67610.00000000', '0.00120000'],
   ['67609.92000000', '0.00008000'],
   ['67609.72000000', '0.00009000'],
   ['67609.54000000', '0.00022000'],
   ['67609.32000000', '0.29027000'],
   ['67609.30000000', '0.70950000'],
   ['67609.00000000', '0.00200000'],
   ['67608.90000000', '0.00473000'],
   ['67608.45000000', '0.02299000'],
   ['67608.24000000', '0.00031000'],
   ['67608.09000000', '0.00591000'],
   ['67608.00000000', '0.00120000'],
   ['67607.76000000', '0.00015000'],
   ['67607.30000000', '0.00200000'],
   ['67607.18000000', '0.00009000'],
   ['67606.64000000', '0.00008000'],
   ['67606.56000000', '0.00017000'],
   ['67606.53000000', '0.00192000'],
   ['67606.49000000', '0.02000000'],
   ['67606.35000000', '0.80758000'],
   ['67606.34000000', '0.70950000'],
   ['67606.00000000', '0.00120000'],
   ['67605.92000000', '0.00260000'],
   ['67605.84000000', '0.09873000'],
   ['67605.67000000', '0.02000000'],
   ['67605.60000000', '1.99757000'],
   ['67605.59000000', '0.02000000'],
   ['67605.58000000', '0.02000000'],
   ['67605.32000000', '0.00597000'],
   ['67605.26000000', '0.00015000'],
   ['67605.03000000', '0.00008000'],
   ['67605.00000000', '0.04000000'],
   ['67604.93000000', '0.00147000'],
   ['67604.92000000', '0.04000000'],
   ['67604.64000000', '0.00009000'],
   ['67604.50000000', '0.00008000'],
   ['67604.41000000', '0.00147000'],
   ['67604.33000000', '0.02000000'],
   ['67604.00000000', '0.00120000']],
  'asks': [['67622.00000000', '0.80824000'],
   ['67622.01000000', '0.00064000'],
   ['67622.19000000', '0.00016000'],
   ['67622.20000000', '0.02629000'],
   ['67623.36000000', '0.00008000'],
   ['67624.20000000', '0.00008000'],
   ['67624.66000000', '0.00151000'],
   ['67624.79000000', '0.00024000'],
   ['67624.80000000', '0.00663000'],
   ['67624.81000000', '0.00008000'],
   ['67624.84000000', '0.00016000'],
   ['67624.85000000', '0.03702000'],
   ['67624.92000000', '0.00016000'],
   ['67624.93000000', '0.03270000'],
   ['67625.29000000', '0.00022000'],
   ['67626.00000000', '0.00200000'],
   ['67626.72000000', '0.00008000'],
   ['67626.81000000', '0.00024000'],
   ['67626.82000000', '0.03728000'],
   ['67627.08000000', '0.02016000'],
   ['67627.50000000', '0.00009000'],
   ['67627.70000000', '0.01711000'],
   ['67627.71000000', '0.03009000'],
   ['67629.07000000', '0.01000000'],
   ['67629.39000000', '0.00739000'],
   ['67629.40000000', '0.00200000'],
   ['67629.75000000', '0.00008000'],
   ['67629.84000000', '0.00012000'],
   ['67630.04000000', '0.00009000'],
   ['67630.08000000', '0.00008000'],
   ['67630.09000000', '0.00008000'],
   ['67630.20000000', '0.00009000'],
   ['67630.42000000', '0.00008000'],
   ['67630.44000000', '0.00015000'],

Create bids df exploded in bids same with asks

In [227]:
bids_df = pd.DataFrame(depth_samples)
bids_df = bids_df[["timestamp", "lastUpdateId", "bids"]].explode("bids")

bids_df["bids_price"], bids_df["bids_volume"] = zip(*bids_df["bids"])

bids_df["bids_price"] = bids_df["bids_price"].astype(float)
bids_df["bids_volume"] = bids_df["bids_volume"].astype(float)

bids_df = bids_df.drop(columns="bids")
bids_df.head()

       timestamp  lastUpdateId   bids_price  bids_volume
0  1773047452780   89730922218 67621.990000     1.185780
0  1773047452780   89730922218 67621.980000     0.000080
0  1773047452780   89730922218 67621.820000     0.133160
0  1773047452780   89730922218 67621.680000     0.000090
0  1773047452780   89730922218 67620.000000     0.000080

In [228]:
asks_df = pd.DataFrame(depth_samples)
asks_df = asks_df[["timestamp", "lastUpdateId", "asks"]].explode("asks")
asks_df["asks_price"], asks_df["asks_volume"] = zip(*asks_df["asks"])

asks_df["asks_price"] = asks_df["asks_price"].astype(float)
asks_df["asks_volume"] = asks_df["asks_volume"].astype(float)

asks_df = asks_df.drop(columns="asks")
asks_df.head()

       timestamp  lastUpdateId   asks_price  asks_volume
0  1773047452780   89730922218 67622.000000     0.916060
0  1773047452780   89730922218 67622.010000     0.000160
0  1773047452780   89730922218 67622.750000     0.000080
0  1773047452780   89730922218 67623.360000     0.000080
0  1773047452780   89730922218 67624.190000     0.000160

now for both asks and bids gets the highest price for each timestamp

In [229]:
max_bid = bids_df.groupby("timestamp")["bids_price"].max().rename("max_bids")
max_ask = asks_df.groupby("timestamp")["asks_price"].max().rename("max_asks")
max_bid_vol = bids_df.groupby("timestamp")["bids_volume"].max().rename("max_bids_vol")
max_ask_vol = asks_df.groupby("timestamp")["asks_volume"].max().rename("max_asks_vol")

In [230]:
combined_df = pd.concat([max_bid, max_ask, max_bid_vol, max_ask_vol], axis=1)
combined_df.reset_index(inplace=True)
combined_df

       timestamp     max_bids     max_asks  max_bids_vol  max_asks_vol
0  1773047452780 67621.990000 67642.000000      2.790720      1.995570
1  1773047454017 67621.990000 67640.160000      1.997570      2.025570
2  1773047455255 67621.990000 67640.000000      1.997570      2.025570
3  1773047456488 67621.990000 67639.220000      1.997570      2.025570
4  1773047457723 67619.200000 67638.640000      1.997570      2.450640

Create features

- timestamp
- best_bid
- best_ask
- mid_price
- spread
- bid_volume
- ask_volume
- imbalance
- microprice
  - to do weighted microprice (maybe add in 5 layers to lob not just best price)
- trade_imbalance

In [231]:
combined_df["mid_price"] = (combined_df["max_bids"] + combined_df["max_asks"]) / 2
combined_df["spread"] = combined_df["max_asks"] - combined_df["max_bids"]

combined_df["imbalance"] = (
    combined_df["max_bids_vol"] - combined_df["max_asks_vol"]
) / (combined_df["max_bids_vol"] + combined_df["max_asks_vol"])


combined_df["liquidity"] = combined_df["max_bids_vol"] + combined_df["max_asks_vol"]
combined_df["microprice"] = (combined_df["max_bids_vol"]*combined_df["max_bids"] + combined_df["max_asks_vol"]*combined_df["max_asks"]) / combined_df["liquidity"]

combined_df

,timestamp,max_bids,max_asks,max_bids_vol,max_asks_vol,mid_price,spread,imbalance,liquidity,microprice
0,1773047452780,67621.990000,67642.000000,2.790720,1.995570,67631.995000,20.010000,0.166131,4.786290,67630.332862
1,1773047454017,67621.990000,67640.160000,1.997570,2.025570,67631.075000,18.170000,-0.006960,4.023140,67631.138229
2,1773047455255,67621.990000,67640.000000,1.997570,2.025570,67630.995000,18.010000,-0.006960,4.023140,67631.057672
3,1773047456488,67621.990000,67639.220000,1.997570,2.025570,67630.605000,17.230000,-0.006960,4.023140,67630.664958
4,1773047457723,67619.200000,67638.640000,1.997570,2.450640,67628.920000,19.440000,-0.101854,4.448210,67629.910025

trade df

In [232]:
trades_df = pd.DataFrame(trades)
trades_df = trades_df.astype({
    "price": float,
    "qty": float,
    "quoteQty": float,
    "time": "int64",
    "isBuyerMaker": bool,
    "isBestMatch": bool,
})
trades_df

,id,price,qty,quoteQty,time,isBuyerMaker,isBestMatch
0,6082553701,67629.760000,0.002360,159.606234,1773047436395,True,True
1,6082553702,67629.760000,0.000080,5.410381,1773047436395,True,True
2,6082553703,67629.760000,0.000080,5.410381,1773047436395,True,True
3,6082553704,67629.760000,0.000080,5.410381,1773047436395,True,True
4,6082553705,67629.760000,0.000080,5.410381,1773047436395,True,True
...,...,...,...,...,...,...,...
995,6082554696,67619.200000,0.000160,10.819072,1773047459575,True,True
996,6082554697,67619.200000,0.000690,46.657248,1773047459575,True,True
997,6082554698,67619.200000,0.000080,5.409536,1773047459575,True,True
998,6082554699,67619.200000,0.000080,5.409536,1773047459575,True,True
999,6082554700,67619.200000,0.066460,4493.972032,1773047459575,True,True

I need to segment trades info into 5 time slots each for each second (need to add in buffer for latency)

In [233]:
pd.set_option("display.float_format", "{:.6f}".format)
trades_df_interval_masks = []

timestamps = combined_df["timestamp"].values
intervals = zip(timestamps[:-1],timestamps[1:])

for t0, t1 in intervals:
    mask = (trades_df["time"]>t0) & (trades_df["time"]<t1)
    trades_df_interval_masks.append(mask)

Check to see if trades correct time intervals

In [234]:
trade_slice_1= trades_df[trades_df_interval_masks[0]]
        
trade_slice_1["time"].describe()

count              13.000000
mean    1773047453762.923096
std               357.401143
min     1773047453136.000000
25%     1773047453951.000000
50%     1773047453951.000000
75%     1773047453951.000000
max     1773047453951.000000
Name: time, dtype: float64

In [235]:
trade_slice_1

,id,price,qty,quoteQty,time,isBuyerMaker,isBestMatch
924,6082554625,67621.990000,0.000080,5.409759,1773047453136,True,True
925,6082554626,67621.990000,0.000080,5.409759,1773047453136,True,True
926,6082554627,67621.990000,0.000950,64.240891,1773047453136,True,True
927,6082554628,67622.000000,0.000160,10.819520,1773047453951,False,True
928,6082554629,67622.000000,0.000160,10.819520,1773047453951,False,True
929,6082554630,67622.000000,0.000160,10.819520,1773047453951,False,True
930,6082554631,67622.000000,0.000690,46.659180,1773047453951,False,True
931,6082554632,67622.000000,0.000080,5.409760,1773047453951,False,True
932,6082554633,67622.000000,0.000160,10.819520,1773047453951,False,True
933,6082554634,67622.000000,0.000080,5.409760,1773047453951,False,True
934,6082554635,67622.000000,0.001800,121.719600,1773047453951,False,True
935,6082554636,67622.000000,0.024990,1689.873780,1773047453951,False,True
936,6082554637,67622.000000,0.025050,1693.931100,1773047453951,False,True

In [236]:
for i, mask in enumerate(trades_df_interval_masks):
    print(i, mask.sum())

0 13
1 3
2 1
3 20

get trade features do for 1 slice then create function to do for all slices
- trade_count
- buy_count
- sell_count
- total_trade_volume
- buy_volume
- sell_volume
- trade_imbalance
- trade_flow_ratio
- avg_trade_size
- max_trade_size
- std_trade_size
- vwap

In [ ]:
trade_count = len(trade_slice_1)
buy_count = len(trade_slice_1[ trade_slice_1["isBuyerMaker"]==True])
sell_count = len(trade_slice_1[ trade_slice_1["isBuyerMaker"]==False])

total_trade_volume = trade_slice_1["qty"].sum()

buy_volume = trade_slice_1.loc[trade_slice_1["isBuyerMaker"]==True,"qty"].sum()
sell_volume = trade_slice_1.loc[trade_slice_1["isBuyerMaker"]==False,"qty"].sum()

trade_imbalance = (buy_volume - sell_volume) / total_trade_volume

trade_flow_ratio = buy_volume/sell_volume

avg_trade_size = total_trade_volume / trade_count

max_trade_size = trade_slice_1["qty"].max()
min_trade_size = trade_slice_1["qty"].min()

std_trade_size = trade_slice_1["qty"].std()

vwap = (trade_slice_1["price"]*trade_slice_1["qty"]).sum() / total_trade_volume

np.float64(67621.9997961058)